eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
POSTS_SERVICE_URI=htpp://posts-service
USER_SERVICE_URI=http://user-service
NOTIFICATION_SERVICE_URI=http://notification-service
CONNECTIONS_SERVICE_URI=http://connections-service
UPLOADER_SERVICE_URI=http://uploader-service
