spring:
  application:
    name: connections-service

  neo4j:
    uri: bolt://${DB_SERVICE:localhost}:7687
    authentication:
      username: ${DB_USERNAME:neo4j}
      password: ${DB_PASSWORD:12345678}

  spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.sanjeevsingh.linkedinProject.*

server:
  port: 9030
  servlet:
    context-path: /connections
