spring:
  application:
    name: connections-service

  neo4j:
    uri: bolt://${DB_SERVICE:localhost}:7687
    authentication:
      username: ${DB_USERNAME:neo4j}
      password: ${DB_PASSWORD:12345678}

  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.sanjeevsingh.linkedinProject.*

server:
  port: 9030
  servlet:
    context-path: /connections
