server.port=9040
server.servlet.context-path =/notification
spring.datasource.url = jdbc:postgresql://${DB_SERVICE:localhost:5432}/${DB_NAME:notificationDB}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
