server:
  port: 9050
  servlet:
    context-path: /uploads
cloudinary:
  cloud-name: dulbyxcpo
  api-key: 642614243534366
  api-secret: 4id-KaWqDVlohAxv2I5nokb_s4o



  
spring:
  servlet:
    multipart:
      enabled: true
       max-file-size: 20MB
       max-request-size: 20MB
